language: node_js
sudo: true
node_js:
  - "stable"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc g++ -y
  - npm install mocha -g
env:
  - TRAVIS=travis CXX=g++
services:
  - mongodb
install:
  - npm install
script:
  - sudo $(which npm) test